"""
Explanation schema — the LLM layer's output contract.

The LLM explanation layer produces ONLY this schema. If the LLM's output fails
to validate against this model, the output is discarded and a deterministic
template is used instead.

The `source` field records which path was taken — 'llm' or 'template' — which
feeds into the dashboard display and the batch metric `llm_fallback_to_template_count`.
This makes the fallback rate a visible, honest metric rather than a hidden failure.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class LLMExplanation(BaseModel):
    """
    Advisory explanation produced by Google Gemini 2.5 Flash, or by a deterministic
    template fallback if the LLM call fails or the API key is unset.

    INVARIANT: This schema contains ONLY language fields (rationale, caveat, fallback).
    It contains NO action field, NO decision field, NO execution instructions.
    The LLM cannot alter what action is taken — only explain it.
    """

    model_config = ConfigDict(protected_namespaces=())

    rationale: str = Field(
        max_length=600,
        description="Plain-English explanation of why this action was chosen, based on failure reason and risk model signals.",
    )
    confidence_caveat: str = Field(
        max_length=350,
        description="Explicit statement of what could go wrong or why confidence is not 100%. Never omitted.",
    )
    fallback_if_wrong: str = Field(
        max_length=350,
        description="Deterministic next step if the recommended action fails (e.g. 'If retry fails, nudge for alternative payment method').",
    )
    source: Literal["llm", "template"] = Field(
        default="llm",
        description="'llm' = generated by Google Gemini; 'template' = deterministic fallback used.",
    )
