"""
FastAPI application — serves both the JSON API and the HTMX dashboard.

Routes:
  JSON API:
    GET  /api/batch/metrics
    GET  /api/batch/transactions
    GET  /api/batch/transaction/{txn_id}
    POST /api/simulate/single
    GET  /api/health

  HTMX (server-rendered HTML):
    GET  /              → index.html (batch summary)
    GET  /transactions  → transactions.html
    GET  /transaction/{txn_id} → transaction_detail.html
    GET  /htmx/transactions    → table partial (HTMX swap target)

  OpenAPI:
    GET  /docs  → Swagger UI (auto-generated by FastAPI)
    GET  /redoc → ReDoc UI
"""

from __future__ import annotations

import logging
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from api.routers import batch, simulate

logging.basicConfig(level=logging.INFO)

app = FastAPI(
    title="Project Meridian — AI Revenue Recovery",
    description=(
        "Bounded AI agent for failed-payment recovery. "
        "The LLM never touches money or state — it only touches language."
    ),
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# Static files + Jinja2 templates
DASHBOARD_DIR = Path(__file__).parent.parent / "dashboard"
app.mount("/static", StaticFiles(directory=str(DASHBOARD_DIR / "static")), name="static")
templates = Jinja2Templates(directory=str(DASHBOARD_DIR / "templates"))

# Register API routers
app.include_router(batch.router, prefix="/api")
app.include_router(simulate.router, prefix="/api")


# ── HTMX page routes ──────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def index(request: Request) -> HTMLResponse:
    """Batch summary dashboard — the first thing a judge sees."""
    from api.dependencies import get_audit_logger
    from simulation.baselines import run_blind_retry_baseline
    from simulation.metrics import compute_metrics
    from ingestion.generator import generate_transactions
    import random

    audit = get_audit_logger()
    record_count = audit.count()

    metrics = None
    if record_count > 0:
        try:
            records = audit.get_all_records()
            # Regenerate the same synthetic set to compute blind-retry baseline
            txns = generate_transactions(n=record_count, random_seed=42)
            blind_rng = random.Random(1042)
            multi_rng = random.Random(2042)
            from simulation.baselines import run_blind_retry_baseline, run_naive_multi_retry_baseline
            recovered_blind = run_blind_retry_baseline(txns, blind_rng)
            recovered_multi = run_naive_multi_retry_baseline(txns, multi_rng)
            metrics = compute_metrics(records, recovered_blind, recovered_multi, seed=42)
        except Exception as exc:
            logging.getLogger(__name__).error("Dashboard metrics failed: %s", exc, exc_info=True)
            metrics = None

    return templates.TemplateResponse(
        "index.html",
        {
            "request": request,
            "metrics": metrics,
            "record_count": record_count,
        },
    )


@app.get("/transactions", response_class=HTMLResponse, include_in_schema=False)
async def transactions_page(request: Request) -> HTMLResponse:
    """Full transaction table with HTMX-powered filtering."""
    return templates.TemplateResponse("transactions.html", {"request": request})


@app.get("/transaction/{txn_id}", response_class=HTMLResponse, include_in_schema=False)
async def transaction_detail_page(request: Request, txn_id: str) -> HTMLResponse:
    """Per-transaction drill-down — full audit record view."""
    from api.dependencies import get_audit_logger

    audit = get_audit_logger()
    record = audit.query_by_txn(txn_id)
    return templates.TemplateResponse(
        "transaction_detail.html",
        {"request": request, "record": record, "txn_id": txn_id},
    )


@app.get("/htmx/transactions", response_class=HTMLResponse, include_in_schema=False)
async def htmx_transactions_partial(
    request: Request,
    filter: str = "all",
    page: int = 1,
) -> HTMLResponse:
    """
    HTMX partial: returns only the transaction table rows.
    Swapped into the transactions page without a full reload.
    """
    from api.dependencies import get_audit_logger

    audit = get_audit_logger()

    filter_overridden: bool | None = None
    filter_recovered: bool | None = None
    filter_action: str | None = None

    if filter == "overridden":
        filter_overridden = True
    elif filter == "recovered":
        filter_recovered = True
    elif filter == "escalated":
        filter_action = "escalate_to_human"
    elif filter == "stopped":
        filter_action = "stop"

    rows, total = audit.get_summary_rows(
        filter_overridden=filter_overridden,
        filter_recovered=filter_recovered,
        filter_action=filter_action,
        page=page,
        page_size=50,
    )
    total_pages = max(1, (total + 49) // 50)

    return templates.TemplateResponse(
        "partials/transaction_rows.html",
        {
            "request": request,
            "rows": rows,
            "total": total,
            "page": page,
            "total_pages": total_pages,
            "filter": filter,
        },
    )
